/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as ProjektiRouteImport } from './routes/projekti'
import { Route as ProizvodiIndexRouteImport } from './routes/proizvodi.index'
import { Route as ProizvodiSlugRouteImport } from './routes/proizvodi.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektiRoute = ProjektiRouteImport.update({
  id: '/projekti',
  path: '/projekti',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodiIndexRoute = ProizvodiIndexRouteImport.update({
  id: '/proizvodi/',
  path: '/proizvodi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodiSlugRoute = ProizvodiSlugRouteImport.update({
  id: '/proizvodi/$slug',
  path: '/proizvodi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/projekti': typeof ProjektiRoute
  '/proizvodi/$slug': typeof ProizvodiSlugRoute
  '/proizvodi/': typeof ProizvodiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/projekti': typeof ProjektiRoute
  '/proizvodi/$slug': typeof ProizvodiSlugRoute
  '/proizvodi': typeof ProizvodiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/projekti': typeof ProjektiRoute
  '/proizvodi/$slug': typeof ProizvodiSlugRoute
  '/proizvodi/': typeof ProizvodiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/kontakt'
    | '/o-nama'
    | '/projekti'
    | '/proizvodi/$slug'
    | '/proizvodi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/kontakt'
    | '/o-nama'
    | '/projekti'
    | '/proizvodi/$slug'
    | '/proizvodi'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/kontakt'
    | '/o-nama'
    | '/projekti'
    | '/proizvodi/$slug'
    | '/proizvodi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  ONamaRoute: typeof ONamaRoute
  ProjektiRoute: typeof ProjektiRoute
  ProizvodiSlugRoute: typeof ProizvodiSlugRoute
  ProizvodiIndexRoute: typeof ProizvodiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekti': {
      id: '/projekti'
      path: '/projekti'
      fullPath: '/projekti'
      preLoaderRoute: typeof ProjektiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodi/': {
      id: '/proizvodi/'
      path: '/proizvodi'
      fullPath: '/proizvodi/'
      preLoaderRoute: typeof ProizvodiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodi/$slug': {
      id: '/proizvodi/$slug'
      path: '/proizvodi/$slug'
      fullPath: '/proizvodi/$slug'
      preLoaderRoute: typeof ProizvodiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  ONamaRoute: ONamaRoute,
  ProjektiRoute: ProjektiRoute,
  ProizvodiSlugRoute: ProizvodiSlugRoute,
  ProizvodiIndexRoute: ProizvodiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
